controller_list:
  - name: fake_base_group_controller
    joints:
      - rotation1
      - rotation2
      - gripper_joint
      - end_effector_joint
initial:  # Define initial robot poses.
  - group: base_group
    pose: initial